/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // App colors
        primary: '#135a46',
        'background-light': '#f8fafc',
        'background-dark': '#0f172a',
        'surface-light': '#ffffff',
        'surface-dark': '#1e293b',
        // Sign In / Material Design 3 tokens
        'on-surface': '#191c1d',
        'outline-variant': '#bfc9c3',
        'secondary-container': '#cee9dc',
        outline: '#707974',
        'primary-fixed': '#adf0d6',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f0f1f2',
        'inverse-surface': '#2e3132',
        'inverse-primary': '#92d4ba',
        'secondary-fixed': '#cee9dc',
        'on-secondary-fixed': '#082018',
        'primary-container': '#135a46',
        'primary-fixed-dim': '#92d4ba',
        secondary: '#4b6359',
        'surface-container-highest': '#e1e3e4',
        'on-primary-container': '#8dcfb6',
        'on-primary-fixed': '#002117',
        'on-secondary-fixed-variant': '#344c42',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'surface-tint': '#276954',
        error: '#ba1a1a',
        'tertiary-container': '#7a3e37',
        'surface-container-low': '#f3f4f5',
        'surface-dim': '#d9dadb',
        'on-background': '#191c1d',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#b2ccc0',
        background: '#f8f9fa',
        'surface-variant': '#e1e3e4',
        'on-secondary-container': '#516a5f',
        'surface-container': '#edeeef',
        'surface-bright': '#f8f9fa',
        'surface': '#f8f9fa',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#3f4944',
        'surface-container-high': '#e7e8e9',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
